version: '2'
services:

  tsuru-redis:
    image: redis    
    ports:
      - 6379:6379
    restart: always   

  tsuru-mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always 

  tsuru-planb:
    image: tsuru/planb:v1 
    ports:
      - 81:80
    external_links:
      - tsuru-redis:tsuru-redis      
    restart: always    
    command: --listen ":80" --read-redis-host=tsuru-redis --write-redis-host=tsuru-redis
    links:
      - tsuru-redis:tsuru-redis

  tsuru-archive-server:
    build: tsuru-archive-server
    ports:
      - 6060:6060 
      - 6161:6161
    external_links:
      - tsuru-mongo:tsuru-mongo 
    command: /usr/bin/archive-server -dir=/var/lib/archive-server/archives -read-http=0.0.0.0:6060 -write-http=127.0.0.1:6161 -mongodb=tsuru-mongo:27017 -dbname=archives
    restart: always    
  
  tsuru-gandalf:
    build: tsuru-gandalf
    environment:
      - ARCHIVE_SERVER_READ=http://tsuru-archive-server:6060 
      - ARCHIVE_SERVER_WRITE=http://tsuru-archive-server:6161 
      - TSURU_HOST=
      - TSURU_TOKEN=
    ports:
      - 8000:8000
    external_links:
      - tsuru-mongo:tsuru-mongo 
      - tsuru-archive-server:tsuru-archive-server 
    #restart: always      

#  tsuru-server:
#    build: tsuru-server
#    ports:
#      - 82:80
#    restart: always  
#    external_links:
#      - tsuru-redis:tsuru-redis        
#      - tsuru-mongo:tsuru-mongo        
#      - tsuru-planb:tsuru-planb 

# tsuru-api 
#   mongo
#   redis
# 
# gandalf
#   mongo
# 
# planb
#   redis
# archiver-server
#  mongo


